[profile.default] # all profiles inherit from this
src = ''
out = 'out/' # default
test = 'test' # default
libs = ['contracts']
cache = false # !important! breaks echidna if cache = true.
# remappings = [
#     '@forge-std/=contracts/forge-std/src/',
#     '@solmate/=contracts/portfolio/lib/solmate/src/',
#     '@solstat/=contracts/solstat/src/',
#     '@uniswap/lib/=contracts/solidity-lib/',
#     '@uniswap/v2-core/=contracts/v2-core/',
#     '@uniswap/v2-periphery/=contracts/v2-periphery/',
# ]
